version: "3.9"

services:
  # Servicio de base de datos
  postgres:
    image: postgres:15
    container_name: incident-db-service
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
        - app-network   

  # Microservicio de incidencias
  incident-service:
    build: ./incident-service
    container_name: incident-service
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file:
      # Cargamos el env de cada microservicio, no machaca, esta el env de la raiz y el del microservicio
      - ./incident-service/.env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      LLM_SERVICE_URL: http://llm-service:8001
    volumes:
      - ./incident-service/logs:/app/logs
    networks:
          - app-network       

  # Microservicio de incidencias
  llm-service:
    build:
      context: ./llm-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      # Cargamos el env de cada microservicio, no machaca, esta el env de la raiz y el del microservicio
      - ./llm-service/.env
    volumes:  # Guardamos en local el cache de Hugging Face para evitar descargar modelos cada vez
      - hf_cache:/root/.cache/huggingface
      - ./llm-service/logs:/app/logs
    networks:
    - app-network
    healthcheck:
          test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8001/health')"]
          interval: 10s
          timeout: 5s
          retries: 10
          start_period: 30s

  # Web que simula el uso de nuestra API
  frontend:
      build: ./web
      container_name: incident-frontend
      ports:
        - "5500:80"
      depends_on:
        - incident-service
      networks:
        - app-network

  # Contenedor para las pruebas de playwright automaticas al levantar los servicios
  playwright-tests:
      build: ./playwright-tests
      container_name: playwright-tests
      depends_on:
            frontend:
              condition: service_started
            llm-service:
              condition: service_healthy
      networks:
        - app-network
      environment:
        - BASE_URL=http://frontend:80
      command: pytest --base-url http://frontend:80

  # Conteneoor para las pruebas de playwright al levantar los servicios
  selenium-tests:
      build: ./selenium-tests
      container_name: selenium-tests
      depends_on:
        frontend:
          condition: service_started
        llm-service:
          condition: service_healthy
      networks:
        - app-network
      environment:
        - BASE_URL=http://frontend:80
        - TESTS_IN_PRODUCTION=True
      command: pytest

volumes:
  postgres_data:
  hf_cache:

networks:
  app-network:
    driver: bridge