# Ocultamos warnings concretos
# Estos warnings no estan relacionados con nuestro codigo ni tests
# Estan relacionados con las librerias utilizadas a las cuales no podemos acceder
# Esta decision es solamente estetica para no confundir al depurar ni al realizar los tests
[pytest]
filterwarnings =
    ignore::DeprecationWarning:swigvarlink
    ignore::DeprecationWarning:SwigPyPacked
    ignore::DeprecationWarning:SwigPyObject
    ignore:builtin type .* has no __module__ attribute